# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "기술블로그"
email: admin@wesome.co.kr
description: >- # this means to ignore newlines until "baseurl:"
  위썸에서 제공하는 서비스들과 신기술을 설명하는 사이트입니다.
# github_username: wesometech
minimal_mistakes_skin: default
search: true
logo: "/assets/images/logo.png"
url: "https://wesometech.github.io"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Asia/Seoul" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
locale: "ko-KR" # https://docs.microsoft.com/en-us/previous-versions/commerce-server/ee825488(v=cs.20)?redirectedfrom=MSDN

google_site_verification: "rwozHFd92xU4P08v2tVrh8gVy4_BAy1ErIHf6WSCbJM"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "wesometech"
  avatar: "/assets/images/avatar.png"
  bio: "Enjoy the Ride"
  location: "서울 구로구 디지털로"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://www.wesome.co.kr"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wesometech"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wesometech"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://www.wesome.co.kr"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
